# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://raw.githubusercontent.com/ssrsub/ssr/master/v2ray

- type: subscribe
  options:
    url: https://raw.githubusercontent.com/fuserh/GoodFreeProxies/master/sub/sub_merge_base64.txt

# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

- type: tgchannel
  options:
    channel: SSRSUC
    num: 500

- type: tgchannel
  options:
    channel: juzibaipiao
    num: 500
    
- type: tgchannel
  options:
    channel: FreeZH
    num: 500
 
- type: tgchannel
  options:
    channel: tgvpn8
    num: 500

- type: tgchannel
  options:
    channel: wxgmrjdcc
    num: 500

- type: tgchannel
  options:
    channel: souqun8816
    num: 500

- type: tgchannel
  options:
    channel: TGvpn6
    num: 500

- type: tgchannel
  options:
    channel: mftizi
    num: 500

- type: tgchannel
  options:
    channel: jiedian_share
    num: 500

- type: tgchannel
  options:
    channel: sola114514
    num: 500

- type: tgchannel
  options:
    channel: baobaojiedian
    num: 500

- type: tgchannel
  options:
    channel: zerobaipiao
    num: 500

- type: tgchannel
  options:
    channel: suyucom
    num: 500
    
- type: tgchannel
  options:
    channel: FreeV2rays
    num: 500

- type: tgchannel
  options:
    channel: fenxbaip1024
    num: 500

- type: tgchannel
  options:
    channel: fenxbaip1024
    num: 500

- type: tgchannel
  options:
    channel: proxyshareCN
    num: 800
    
- type: tgchannel
  options:
    channel: jiedian_share
    num: 800

- type: tgchannel
  options:
    channel: heinuhome
    num: 500
    
- type: tgchannel
  options:
    channel: mftizi
    num: 500



# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://raw.githubusercontent.com/du5/free/master/file/0909/Clash.yaml

# 某个网站抓取
- type: web-freessrxyz
  options:
