# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: pull
      run: git clone https://github.com/gffice/runproxypool.git
    - name: chmod
      run: |
        chmod 777 debug-github-actions.sh
    - name: Start SSH via Ngrok
      run: ./debug-github-actions.sh
      env:
        # After sign up on the https://ngrok.com/
        # You can find this token here: https://dashboard.ngrok.com/get-started/setup
        NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}

    #- name: Build
      #run: go build -v ./...

    - name: Test
      run: go run main.go -c ./config/config.yaml
